#!/usr/bin/env node
/**
 * Central Pro — vendor activation key tool.
 *
 * Usage (run from the project root):
 *   node scripts/license/keygen.mts init                 create YOUR signing keys (once)
 *   node scripts/license/keygen.mts issue --request XXXX-XXXX-XXXX-XXXX [--tier PROFESSIONAL] [--days 0] [--customer "Name"]
 *   node scripts/license/keygen.mts verify --request ... --key ...
 *   node scripts/license/keygen.mts list
 *
 * --days 0 (default) = lifetime license. --days 365 = one year from today.
 * The private key lives in ./license-keys/ — keep it secret and back it up.
 * If you lose it you cannot issue keys for installed copies.
 */
import { createPrivateKey, createPublicKey, generateKeyPairSync, sign, verify } from 'node:crypto'
import { appendFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  decodePayload,
  decodeRequestCode,
  encodePayload,
  formatActivationKey,
  licenseExpiry,
  signingMessage,
  splitActivationKey,
  TIER_CODES,
  type PaidTier
} from '../../src/shared/license-codec.ts'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../..')
const KEY_DIR = process.env.CENTRAL_LICENSE_KEY_DIR ?? join(ROOT, 'license-keys')
const PRIVATE_KEY = join(KEY_DIR, 'private-key.pem')
const LEDGER = join(KEY_DIR, 'issued-keys.csv')
const PUBLIC_KEY_TS = join(ROOT, 'src/main/license/public-key.ts')
const DEV_PRIVATE_KEY = join(ROOT, 'scripts/license/dev-private-key.pem')

function args(): Record<string, string> {
  const out: Record<string, string> = {}
  const a = process.argv.slice(3)
  for (let i = 0; i < a.length; i++) {
    const k = a[i]!
    if (k.startsWith('--')) {
      out[k.slice(2)] = a[i + 1] && !a[i + 1]!.startsWith('--') ? a[++i]! : 'true'
    }
  }
  return out
}

function fail(msg: string): never {
  console.error(`\n✖ ${msg}\n`)
  process.exit(1)
}

function loadPrivateKey(useDev: boolean) {
  const file = useDev ? DEV_PRIVATE_KEY : PRIVATE_KEY
  if (!existsSync(file)) fail(`Private key not found at ${file}. Run "init" first.`)
  return createPrivateKey(readFileSync(file, 'utf8'))
}

function nextSerial(): number {
  if (!existsSync(LEDGER)) return 1
  const lines = readFileSync(LEDGER, 'utf8').trim().split('\n').slice(1)
  const max = lines.reduce((m, l) => Math.max(m, Number(l.split(',')[1]) || 0), 0)
  return (max + 1) % 0xffff || 1
}

function writePublicKeyModule(pem: string): void {
  const body = `// Public key used to verify activation keys. Generated by scripts/license/keygen.mts.
// Safe to commit. The matching private key must never be committed.
export const LICENSE_PUBLIC_KEY_PEM = \`${pem.trim()}\`
`
  writeFileSync(PUBLIC_KEY_TS, body)
}

const command = process.argv[2]
const opts = args()

switch (command) {
  case 'init': {
    if (existsSync(PRIVATE_KEY) && opts.force !== 'true') fail(`${PRIVATE_KEY} already exists. Use --force to replace it (old keys stop working!).`)
    mkdirSync(KEY_DIR, { recursive: true })
    const { publicKey, privateKey } = generateKeyPairSync('ed25519')
    writeFileSync(PRIVATE_KEY, privateKey.export({ type: 'pkcs8', format: 'pem' }), { mode: 0o600 })
    writePublicKeyModule(publicKey.export({ type: 'spki', format: 'pem' }).toString())
    if (!existsSync(LEDGER)) writeFileSync(LEDGER, 'issuedAt,serial,tier,days,requestCode,customer,key\n')
    console.log(`\n✔ Production signing keys created.
  Private key : ${PRIVATE_KEY}   (BACK THIS UP. NEVER SHARE OR COMMIT IT)
  Public key  : written into src/main/license/public-key.ts
  Rebuild the app so installers verify keys with your public key.\n`)
    break
  }
  case 'issue': {
    const request = opts.request ?? fail('--request is required')
    const machineId = decodeRequestCode(request) ?? fail('Request code is invalid (check for typos).')
    const tier = (opts.tier ?? 'PROFESSIONAL').toUpperCase() as PaidTier
    if (!(tier in TIER_CODES)) fail(`--tier must be one of ${Object.keys(TIER_CODES).join(', ')}`)
    const validDays = Number(opts.days ?? 0)
    if (!Number.isInteger(validDays) || validDays < 0 || validDays > 65535) fail('--days must be 0..65535')
    const useDev = opts.dev === 'true'
    const serial = opts.serial ? Number(opts.serial) : nextSerial()
    const issuedAt = new Date()
    const payload = encodePayload({ tier, machineId, issuedAt, validDays, serial })
    const signature = sign(null, Buffer.from(signingMessage(payload)), loadPrivateKey(useDev))
    const key = formatActivationKey(payload, new Uint8Array(signature))
    if (!useDev) {
      mkdirSync(KEY_DIR, { recursive: true })
      if (!existsSync(LEDGER)) writeFileSync(LEDGER, 'issuedAt,serial,tier,days,requestCode,customer,key\n')
      const customer = (opts.customer ?? '').replace(/[,\n]/g, ' ')
      appendFileSync(LEDGER, `${issuedAt.toISOString()},${serial},${tier},${validDays},${request},${customer},${key}\n`)
    }
    const exp = licenseExpiry(decodePayload(payload)!)
    console.log(`\nActivation key for ${request}  (${tier}, ${validDays === 0 ? 'lifetime' : `${validDays} days → ${exp!.toISOString().slice(0, 10)}`}, serial #${serial})\n`)
    console.log(key)
    console.log('')
    break
  }
  case 'verify': {
    const machineId = decodeRequestCode(opts.request ?? '') ?? fail('Request code is invalid')
    const parts = splitActivationKey(opts.key ?? '') ?? fail('Key format is invalid')
    const payload = decodePayload(parts.payload) ?? fail('Key payload is invalid')
    const pem = readFileSync(PUBLIC_KEY_TS, 'utf8').match(/`([\s\S]+)`/)![1]!
    const ok = verify(null, Buffer.from(signingMessage(parts.payload)), createPublicKey(pem), Buffer.from(parts.signature))
    const machineOk = Buffer.from(payload.machineId).equals(Buffer.from(machineId))
    console.log({ signatureValid: ok, machineMatches: machineOk, tier: payload.tier, issuedAt: payload.issuedAt, validDays: payload.validDays, serial: payload.serial })
    process.exit(ok && machineOk ? 0 : 2)
    break
  }
  case 'list': {
    console.log(existsSync(LEDGER) ? readFileSync(LEDGER, 'utf8') : 'No keys issued yet.')
    break
  }
  default:
    console.log(readFileSync(fileURLToPath(import.meta.url), 'utf8').split('\n').slice(2, 15).join('\n'))
}
