#!/usr/bin/env node
/**
 * Central Pro — vendor activation key tool.
 *
 * Usage (run from the project root):
 *   node scripts/license/keygen.mts init                 create YOUR signing keys (once)
 *   node scripts/license/keygen.mts issue --request XXXX-XXXX-XXXX-XXXX --plan quarterly [--periods 1|2|4] [--customer "Name"]
 *   node scripts/license/keygen.mts issue --request XXXX-XXXX-XXXX-XXXX [--tier PROFESSIONAL] [--days 0] [--customer "Name"]
 *   node scripts/license/keygen.mts recover --code XXXX-XXXX-XXXX-XXXX-XXXX-XXX   owner password recovery key
 *   node scripts/license/keygen.mts verify --request ... --key ...
 *   node scripts/license/keygen.mts list
 *
 * --plan quarterly = the 3-month subscription (src/shared/subscription.ts); renewals add on top.
 * --periods 2 = 6 months in one key, --periods 4 = a year (any app version accepts it).
 * --days 0 (default) = lifetime license. --days 365 = one year from today.
 * The private key lives in ./license-keys/ — keep it secret and back it up.
 * If you lose it you cannot issue keys for installed copies.
 */
import { createPrivateKey, createPublicKey, generateKeyPairSync, scryptSync, sign, verify, type KeyObject } from 'node:crypto'
import { appendFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  decodePayload,
  decodeRecoveryCode,
  decodeRequestCode,
  encodePayload,
  encodeRecoveryPayload,
  recoverySigningMessage,
  formatActivationKey,
  licenseExpiry,
  signingMessage,
  splitActivationKey,
  TIER_CODES,
  type PaidTier
} from '../../src/shared/license-codec.ts'
import { SUBSCRIPTION } from '../../src/shared/subscription.ts'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../..')
const KEY_DIR = process.env.CENTRAL_LICENSE_KEY_DIR ?? join(ROOT, 'license-keys')
const PRIVATE_KEY = join(KEY_DIR, 'private-key.pem')
const LEDGER = join(KEY_DIR, 'issued-keys.csv')
const PUBLIC_KEY_TS = join(ROOT, 'src/main/license/public-key.ts')
const DEV_PRIVATE_KEY = join(ROOT, 'scripts/license/dev-private-key.pem')

function args(): Record<string, string> {
  const out: Record<string, string> = {}
  const a = process.argv.slice(3)
  for (let i = 0; i < a.length; i++) {
    const k = a[i]!
    if (k.startsWith('--')) {
      out[k.slice(2)] = a[i + 1] && !a[i + 1]!.startsWith('--') ? a[++i]! : 'true'
    }
  }
  return out
}

function fail(msg: string): never {
  console.error(`\n✖ ${msg}\n`)
  process.exit(1)
}

/**
 * The signing key is either an Ed25519 PEM (from `init`) or any secret text
 * (e.g. a long passphrase saved as the LICENSE_PRIVATE_KEY secret), which is
 * stretched with scrypt into an Ed25519 key. The same text always gives the
 * same key, so it must be long and random: anyone who guesses it can issue keys.
 */
export function keyFromSecret(raw: string): KeyObject {
  try {
    const pem = createPrivateKey(raw)
    if (pem.asymmetricKeyType === 'ed25519') return pem
  } catch {
    /* not a PEM key: treat as secret text */
  }
  const secret = raw.trim()
  if (secret.length < 12) fail('The license secret is too short (use at least 20 random characters).')
  const seed = scryptSync(secret, 'central-pro:license-signing-key:v1', 32, { N: 1 << 17, r: 8, p: 1, maxmem: 256 * 1024 * 1024 })
  // PKCS#8 wrapper for a raw Ed25519 seed
  const der = Buffer.concat([Buffer.from('302e020100300506032b657004220420', 'hex'), seed])
  return createPrivateKey({ key: der, format: 'der', type: 'pkcs8' })
}

function loadPrivateKey(useDev: boolean) {
  const file = useDev ? DEV_PRIVATE_KEY : PRIVATE_KEY
  if (!existsSync(file)) fail(`Private key not found at ${file}. Run "init" first.`)
  return keyFromSecret(readFileSync(file, 'utf8'))
}

const publicPem = (k: KeyObject) => (createPublicKey(k).export({ type: 'spki', format: 'pem' }) as string).trim()

function nextSerial(): number {
  if (!existsSync(LEDGER)) return 1
  const lines = readFileSync(LEDGER, 'utf8').trim().split('\n').slice(1)
  const max = lines.reduce((m, l) => Math.max(m, Number(l.split(',')[1]) || 0), 0)
  return (max + 1) % 0xffff || 1
}

function writePublicKeyModule(pem: string): void {
  const body = `// Public key used to verify activation keys. Generated by scripts/license/keygen.mts.
// Safe to commit. The matching private key must never be committed.
export const LICENSE_PUBLIC_KEY_PEM = \`${pem.trim()}\`
`
  writeFileSync(PUBLIC_KEY_TS, body)
}

const command = process.argv[2]
const opts = args()

switch (command) {
  case 'init': {
    if (existsSync(PRIVATE_KEY) && opts.force !== 'true') fail(`${PRIVATE_KEY} already exists. Use --force to replace it (old keys stop working!).`)
    mkdirSync(KEY_DIR, { recursive: true })
    const { publicKey, privateKey } = generateKeyPairSync('ed25519')
    writeFileSync(PRIVATE_KEY, privateKey.export({ type: 'pkcs8', format: 'pem' }), { mode: 0o600 })
    writePublicKeyModule(publicKey.export({ type: 'spki', format: 'pem' }).toString())
    if (!existsSync(LEDGER)) writeFileSync(LEDGER, 'issuedAt,serial,tier,days,requestCode,customer,key\n')
    console.log(`\n✔ Production signing keys created.
  Private key : ${PRIVATE_KEY}   (BACK THIS UP. NEVER SHARE OR COMMIT IT)
  Public key  : written into src/main/license/public-key.ts
  Rebuild the app so installers verify keys with your public key.\n`)
    break
  }
  case 'issue': {
    const request = opts.request ?? fail('--request is required')
    const machineId = decodeRequestCode(request) ?? fail('Request code is invalid (check for typos).')
    const quarterly = opts.plan === 'quarterly'
    if (opts.plan && !quarterly) fail('--plan must be "quarterly"')
    const tier = (quarterly ? SUBSCRIPTION.tier : (opts.tier ?? 'PROFESSIONAL').toUpperCase()) as PaidTier
    if (!(tier in TIER_CODES)) fail(`--tier must be one of ${Object.keys(TIER_CODES).join(', ')}`)
    const periods = Number(opts.periods ?? 1)
    if (!quarterly && opts.periods) fail('--periods needs --plan quarterly')
    if (!Number.isInteger(periods) || periods < 1 || periods > 8) fail('--periods must be 1..8')
    const validDays = quarterly ? SUBSCRIPTION.days * periods : Number(opts.days ?? 0)
    if (!Number.isInteger(validDays) || validDays < 0 || validDays > 65535) fail('--days must be 0..65535')
    const useDev = opts.dev === 'true'
    const serial = opts.serial ? Number(opts.serial) : nextSerial()
    const issuedAt = new Date()
    const payload = encodePayload({ tier, machineId, issuedAt, validDays, serial })
    const privateKey = loadPrivateKey(useDev)
    if (!useDev) {
      // A key signed by a different private key would never activate the shipped app.
      const shipped = readFileSync(PUBLIC_KEY_TS, 'utf8').match(/`([\s\S]+)`/)![1]!.trim()
      const mine = publicPem(privateKey)
      if (shipped !== mine) fail('This private key does not match the public key built into the app (src/main/license/public-key.ts). Keys made with it would be rejected.')
    }
    const signature = sign(null, Buffer.from(signingMessage(payload)), privateKey)
    const key = formatActivationKey(payload, new Uint8Array(signature))
    if (!useDev) {
      mkdirSync(KEY_DIR, { recursive: true })
      if (!existsSync(LEDGER)) writeFileSync(LEDGER, 'issuedAt,serial,tier,days,requestCode,customer,key\n')
      const customer = (opts.customer ?? '').replace(/[,\n]/g, ' ')
      appendFileSync(LEDGER, `${issuedAt.toISOString()},${serial},${tier},${validDays},${request},${customer},${key}\n`)
    }
    const exp = licenseExpiry(decodePayload(payload)!)
    console.log(`\nActivation key for ${request}  (${tier}, ${validDays === 0 ? 'lifetime' : `${validDays} days → ${exp!.toISOString().slice(0, 10)}`}, serial #${serial})\n`)
    console.log(key)
    console.log('')
    if (process.env.GITHUB_STEP_SUMMARY) {
      const tierAr = quarterly
        ? `اشتراك ${SUBSCRIPTION.months * periods} شهور — ${SUBSCRIPTION.priceEgp * periods} جنيه (كل المميزات، بدون حد للمستخدمين)`
        : { BASIC: 'أساسي (حتى 3 مستخدمين)', PROFESSIONAL: 'احترافي (حتى 15 مستخدم)', ENTERPRISE: 'مؤسسات (بدون حد)' }[tier]
      const until =
        validDays === 0
          ? 'مدى الحياة ♾️'
          : quarterly
            ? `${validDays} يوم — بتتضاف على الأيام الباقية عند العميل (لو اشتراكه خلص: من النهارده لحد ${exp!.toISOString().slice(0, 10)})`
            : `${validDays} يوم — حتى ${exp!.toISOString().slice(0, 10)}`
      appendFileSync(
        process.env.GITHUB_STEP_SUMMARY,
        [
          '## 🔑 مفتاح التفعيل جاهز',
          '',
          '| | |',
          '|---|---|',
          `| كود الطلب | \`${request.toUpperCase()}\` |`,
          `| ${quarterly ? 'الباقة' : 'نوع الترخيص'} | ${tierAr} |`,
          `| المدة | ${until} |`,
          `| الرقم التسلسلي | #${serial} |`,
          `| تاريخ الإصدار | ${issuedAt.toISOString().slice(0, 10)} |`,
          '',
          '**انسخ المفتاح ده كله وابعته للعميل:**',
          '',
          '```',
          key,
          '```',
          '',
          '> العميل يفتح **الإعدادات ← الترخيص** (أو شاشة التفعيل) ويلصق المفتاح ويضغط **تفعيل**. المفتاح يشتغل على الجهاز ده بس ومن غير إنترنت.',
          ''
        ].join('\n')
      )
    }
    break
  }
  case 'recover': {
    // A customer forgot the owner password: the login screen shows a recovery code.
    const code = opts.code ?? fail('--code is required')
    const parsed = decodeRecoveryCode(code) ?? fail('Recovery code is invalid (check for typos — it has 23 characters).')
    const useDev = opts.dev === 'true'
    const privateKey = loadPrivateKey(useDev)
    if (!useDev) {
      const shipped = readFileSync(PUBLIC_KEY_TS, 'utf8').match(/`([\s\S]+)`/)![1]!.trim()
      if (shipped !== publicPem(privateKey)) fail('This private key does not match the public key built into the app.')
    }
    const issuedAt = new Date()
    const payload = encodeRecoveryPayload({ machineId: parsed.machineId, nonce: parsed.nonce, issuedAt })
    const key = formatActivationKey(payload, new Uint8Array(sign(null, Buffer.from(recoverySigningMessage(payload)), privateKey)))
    console.log(`\nPassword recovery key for ${code.toUpperCase()} (valid 7 days, one use)\n`)
    console.log(key)
    console.log('')
    if (process.env.GITHUB_STEP_SUMMARY) {
      appendFileSync(
        process.env.GITHUB_STEP_SUMMARY,
        [
          '## 🔐 مفتاح استعادة كلمة المرور جاهز',
          '',
          `كود الاستعادة: \`${code.toUpperCase()}\` · صالح 7 أيام · يتستخدم مرة واحدة على الجهاز ده بس`,
          '',
          '**انسخ المفتاح ده كله وابعته للعميل:**',
          '',
          '```',
          key,
          '```',
          '',
          '> العميل في شاشة الدخول ← **نسيت كلمة المرور؟** ← يلصق المفتاح ← يختار كلمة مرور جديدة.',
          '> ⚠️ اتأكد إن اللي طالب المفتاح هو صاحب المحل فعلاً (كلمه على رقمه المعروف) قبل ما تبعته.',
          ''
        ].join('\n')
      )
    }
    break
  }
  case 'verify': {
    const machineId = decodeRequestCode(opts.request ?? '') ?? fail('Request code is invalid')
    const parts = splitActivationKey(opts.key ?? '') ?? fail('Key format is invalid')
    const payload = decodePayload(parts.payload) ?? fail('Key payload is invalid')
    const pem = readFileSync(PUBLIC_KEY_TS, 'utf8').match(/`([\s\S]+)`/)![1]!
    const ok = verify(null, Buffer.from(signingMessage(parts.payload)), createPublicKey(pem), Buffer.from(parts.signature))
    const machineOk = Buffer.from(payload.machineId).equals(Buffer.from(machineId))
    console.log({ signatureValid: ok, machineMatches: machineOk, tier: payload.tier, issuedAt: payload.issuedAt, validDays: payload.validDays, serial: payload.serial })
    process.exit(ok && machineOk ? 0 : 2)
    break
  }
  case 'public-key': {
    // Public half of the signing key (safe to show). --write embeds it in the app.
    const pem = publicPem(loadPrivateKey(false))
    if (opts.write === 'true') {
      writePublicKeyModule(pem + '\n')
      console.log('✔ Public key written into src/main/license/public-key.ts')
    }
    console.log(pem)
    break
  }
  case 'list': {
    console.log(existsSync(LEDGER) ? readFileSync(LEDGER, 'utf8') : 'No keys issued yet.')
    break
  }
  default:
    console.log(readFileSync(fileURLToPath(import.meta.url), 'utf8').split('\n').slice(2, 15).join('\n'))
}
