/**
 * Offline activation key format (v1). Pure byte encoding — signing and
 * verification (Ed25519) happen in the main process / vendor keygen tool.
 *
 * Request code (shown by the app, sent by the customer to the vendor):
 *   10 bytes = machineId(8) + check(2)  → 16 Crockford base32 chars
 *
 * Activation key (generated by the vendor):
 *   payload(16) + Ed25519 signature(64) = 80 bytes → 128 base32 chars
 *   payload: [0] version  [1] tier  [2..9] machineId
 *            [10..11] issue day  [12..13] valid days (0 = lifetime)
 *            [14..15] license serial
 */

export const LICENSE_KEY_VERSION = 1
export const LICENSE_EPOCH_MS = Date.UTC(2024, 0, 1)
export const LICENSE_SIGNING_DOMAIN = 'CENTRAL-PRO-LICENSE-V1:'
const DAY_MS = 86_400_000

export const TIER_CODES = { BASIC: 1, PROFESSIONAL: 2, ENTERPRISE: 3 } as const
export type PaidTier = keyof typeof TIER_CODES

const ALPHABET = '0123456789ABCDEFGHJKMNPQRSTVWXYZ'

export function base32Encode(bytes: Uint8Array): string {
  let bits = 0
  let value = 0
  let out = ''
  for (const b of bytes) {
    value = (value << 8) | b
    bits += 8
    while (bits >= 5) {
      out += ALPHABET[(value >>> (bits - 5)) & 31]
      bits -= 5
    }
  }
  if (bits > 0) out += ALPHABET[(value << (5 - bits)) & 31]
  return out
}

export function base32Decode(input: string): Uint8Array | null {
  const clean = input
    .toUpperCase()
    .replace(/[\s\-_]/g, '')
    .replace(/[IL]/g, '1')
    .replace(/O/g, '0')
  const out: number[] = []
  let bits = 0
  let value = 0
  for (const ch of clean) {
    const idx = ALPHABET.indexOf(ch)
    if (idx < 0) return null
    value = ((value << 5) | idx) & 0xffff
    bits += 5
    if (bits >= 8) {
      out.push((value >>> (bits - 8)) & 0xff)
      bits -= 8
    }
  }
  return new Uint8Array(out)
}

export function groupString(s: string, size: number): string {
  return s.match(new RegExp(`.{1,${size}}`, 'g'))?.join('-') ?? s
}

/** Small deterministic checksum (Fletcher-16) used to catch typos. */
export function fletcher16(data: Uint8Array): [number, number] {
  let a = 0
  let b = 0
  for (const byte of data) {
    a = (a + byte) % 255
    b = (b + a) % 255
  }
  return [a, b]
}

export function encodeRequestCode(machineId: Uint8Array): string {
  if (machineId.length !== 8) throw new Error('machineId must be 8 bytes')
  const [a, b] = fletcher16(machineId)
  const bytes = new Uint8Array(10)
  bytes.set(machineId, 0)
  bytes[8] = a
  bytes[9] = b
  return groupString(base32Encode(bytes), 4)
}

export function decodeRequestCode(code: string): Uint8Array | null {
  const bytes = base32Decode(code)
  if (!bytes || bytes.length !== 10) return null
  const id = bytes.slice(0, 8)
  const [a, b] = fletcher16(id)
  if (bytes[8] !== a || bytes[9] !== b) return null
  return id
}

export interface LicensePayload {
  version: number
  tier: PaidTier
  machineId: Uint8Array
  issuedAt: Date
  validDays: number
  serial: number
}

export function encodePayload(p: Omit<LicensePayload, 'version'>): Uint8Array {
  const buf = new Uint8Array(16)
  const view = new DataView(buf.buffer)
  buf[0] = LICENSE_KEY_VERSION
  buf[1] = TIER_CODES[p.tier]
  buf.set(p.machineId, 2)
  const day = Math.floor((p.issuedAt.getTime() - LICENSE_EPOCH_MS) / DAY_MS)
  if (day < 0 || day > 0xffff) throw new Error('issue date out of range')
  if (p.validDays < 0 || p.validDays > 0xffff) throw new Error('validDays out of range')
  if (p.serial < 0 || p.serial > 0xffff) throw new Error('serial out of range')
  view.setUint16(10, day)
  view.setUint16(12, p.validDays)
  view.setUint16(14, p.serial)
  return buf
}

export function decodePayload(buf: Uint8Array): LicensePayload | null {
  if (buf.length !== 16 || buf[0] !== LICENSE_KEY_VERSION) return null
  const tier = (Object.keys(TIER_CODES) as PaidTier[]).find((t) => TIER_CODES[t] === buf[1])
  if (!tier) return null
  const view = new DataView(buf.buffer, buf.byteOffset, buf.byteLength)
  return {
    version: buf[0],
    tier,
    machineId: buf.slice(2, 10),
    issuedAt: new Date(LICENSE_EPOCH_MS + view.getUint16(10) * DAY_MS),
    validDays: view.getUint16(12),
    serial: view.getUint16(14)
  }
}

/** Bytes that are actually signed (domain-separated). */
export function signingMessage(payload: Uint8Array): Uint8Array {
  const prefix = new TextEncoder().encode(LICENSE_SIGNING_DOMAIN)
  const msg = new Uint8Array(prefix.length + payload.length)
  msg.set(prefix, 0)
  msg.set(payload, prefix.length)
  return msg
}

export function formatActivationKey(payload: Uint8Array, signature: Uint8Array): string {
  const all = new Uint8Array(payload.length + signature.length)
  all.set(payload, 0)
  all.set(signature, payload.length)
  return groupString(base32Encode(all), 8)
}

export function splitActivationKey(key: string): { payload: Uint8Array; signature: Uint8Array } | null {
  const bytes = base32Decode(key)
  if (!bytes || bytes.length !== 80) return null
  return { payload: bytes.slice(0, 16), signature: bytes.slice(16) }
}

export function licenseExpiry(p: LicensePayload): Date | null {
  return p.validDays === 0 ? null : new Date(p.issuedAt.getTime() + p.validDays * DAY_MS)
}

export function bytesEqual(a: Uint8Array, b: Uint8Array): boolean {
  if (a.length !== b.length) return false
  let diff = 0
  for (let i = 0; i < a.length; i++) diff |= a[i]! ^ b[i]!
  return diff === 0
}

// ── Owner password recovery (vendor-signed, offline) ──
//
// Recovery code (shown on the login screen, sent to the vendor):
//   machineId(8) + nonce(4) + check(2) = 14 bytes → 23 base32 chars
// Recovery key (from the vendor): payload(16) + Ed25519 signature(64), like an
// activation key but signed under a different domain so neither can stand in
// for the other. payload: [0] version [1] 'R' [2..9] machineId [10..13] nonce
// [14..15] issue day.

export const RECOVERY_SIGNING_DOMAIN = 'CENTRAL-PRO-RECOVERY-V1:'
const RECOVERY_TYPE = 0x52 // 'R'

export function encodeRecoveryCode(machineId: Uint8Array, nonce: Uint8Array): string {
  if (machineId.length !== 8 || nonce.length !== 4) throw new Error('bad recovery code parts')
  const body = new Uint8Array(12)
  body.set(machineId, 0)
  body.set(nonce, 8)
  const [a, b] = fletcher16(body)
  const bytes = new Uint8Array(14)
  bytes.set(body, 0)
  bytes[12] = a
  bytes[13] = b
  return groupString(base32Encode(bytes), 4)
}

export function decodeRecoveryCode(code: string): { machineId: Uint8Array; nonce: Uint8Array } | null {
  const bytes = base32Decode(code)
  if (!bytes || bytes.length !== 14) return null
  const body = bytes.slice(0, 12)
  const [a, b] = fletcher16(body)
  if (bytes[12] !== a || bytes[13] !== b) return null
  return { machineId: body.slice(0, 8), nonce: body.slice(8, 12) }
}

export interface RecoveryPayload {
  machineId: Uint8Array
  nonce: Uint8Array
  issuedAt: Date
}

export function encodeRecoveryPayload(p: RecoveryPayload): Uint8Array {
  const buf = new Uint8Array(16)
  buf[0] = LICENSE_KEY_VERSION
  buf[1] = RECOVERY_TYPE
  buf.set(p.machineId, 2)
  buf.set(p.nonce, 10)
  const day = Math.floor((p.issuedAt.getTime() - LICENSE_EPOCH_MS) / DAY_MS)
  if (day < 0 || day > 0xffff) throw new Error('issue date out of range')
  new DataView(buf.buffer).setUint16(14, day)
  return buf
}

export function decodeRecoveryPayload(buf: Uint8Array): RecoveryPayload | null {
  if (buf.length !== 16 || buf[0] !== LICENSE_KEY_VERSION || buf[1] !== RECOVERY_TYPE) return null
  const view = new DataView(buf.buffer, buf.byteOffset, buf.byteLength)
  return { machineId: buf.slice(2, 10), nonce: buf.slice(10, 14), issuedAt: new Date(LICENSE_EPOCH_MS + view.getUint16(14) * DAY_MS) }
}

export function recoverySigningMessage(payload: Uint8Array): Uint8Array {
  const prefix = new TextEncoder().encode(RECOVERY_SIGNING_DOMAIN)
  const msg = new Uint8Array(prefix.length + payload.length)
  msg.set(prefix, 0)
  msg.set(payload, prefix.length)
  return msg
}
