// Public key used to verify activation keys. Generated by scripts/license/keygen.mts.
// Safe to commit. The matching private key must never be committed.
export const LICENSE_PUBLIC_KEY_PEM = `-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEAAZyA7wEnbzrpIUP+qKYd13FYoeUHSr+PyJgEX41mAg4=
-----END PUBLIC KEY-----`
