// Public key used to verify activation keys. Generated by scripts/license/keygen.ts.
// Safe to commit. The matching private key must never be committed.
// NOTE: this is the DEVELOPMENT key. Run `npm run license:init` before building a release.
export const LICENSE_PUBLIC_KEY_PEM = `-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEAY0qd3bnYHj4LWoJ5Pgx06aO5xdqkowsc/Zuc+DEsstA=
-----END PUBLIC KEY-----`
