// Public key used to verify activation keys. Generated by scripts/license/keygen.mts.
// Safe to commit. The matching private key must never be committed.
export const LICENSE_PUBLIC_KEY_PEM = `-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEA5bbvQwVEdO58W8xgSO1n0id5pdM28qKsSad0TOlILKE=
-----END PUBLIC KEY-----`
